# Generated by Django 4.0 on 2023-02-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
